{{ if .Values.allowNFS.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grader-pvc-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: grader-pv-{{ .Release.Name }}
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
{{ end }}