{{ if .Values.keyCloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: keycloak
  name: keycloak
  namespace:  {{ .Release.Namespace }}
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "https"
      port: 8443
      targetPort: 8443
  selector:
    io.kompose.service: keycloak
status:
  loadBalancer: {}

{{ end }}
