{{ if .Values.keyCloak.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: keycloak
  name: keycloak
  namespace:  {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
      - name: keycloak
        image: docker.io/jboss/keycloak:latest
        envFrom:
        - configMapRef:
            name: keycloak-postgres-configmap-{{ .Release.Namespace }}
        ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
        readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
      restartPolicy: Always

{{ end }}
