# IllumiDesk configuration values
# --------------------
# Create and use roles and service accounts on an RBAC enabled cluster.
rbac:
  enabled: true

## String to partially override illumidesk.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override illumidesk.fullname template
##
# fullnameOverride:

jupyterhub:
# Helm config for jupyterhub goes here
# See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml
  hub:
    auth:
      type: custom
      state:
        enabled: true
        cryptoKey: 'dbd8cc4866eff335ab70ebd8337827663c1ab7319b7eb3c3453a9ad20002a0a0'
      admin:
        access: true
        users:
          - admin
      custom:
        className: 'illumidesk.authenticators.authenticator.LTI13Authenticator'
    db:
      type: postgres
    extraConfig:
      logoConfig: |
        c.JupyterHub.logo_file = "/srv/jupyterhub/illumidesk-80.png"
    image:
      name: illumidesk/jupyterhub
      tag: k8s-latest
      pullPolicy: Always
    shutdownOnLogout: true
  proxy:
    https:
      enabled: true
    secretToken: ''
    service:
      # ports:
      #   nodePort: 8080
      type: ClusterIP
  singleuser:
    cmd: start-singleuser.sh
    extraEnv:
      CHOWN_HOME: 'yes'
      Editor: vim
    fsGid: 0
    uid: 0
    image:
      name: illumidesk/illumidesk-notebook
      tag: latest
      pullPolicy: Always

postgresql:
  enabled: false

datadog:
  enabled: false
  targetSystem: "linux"
  datadog:
    apiKey: ''
    site: ''
    clusterName: ''
    logs:
      enabled: true
      containerCollectAll: true
    clusterAgent:
      enabled: true
      token: ''
      metricsProvider:
        enabled: true

albIngressController:
  enabled: false
  enableIRSA: false

albIngress:
  enabled: false

allowExternalDNS:
  enabled: false
  enableIRSA: false

nginxIngressController:
  enabled: false
  host: 'test'

nginxIngress:
  enabled: false

allowNFS:
  enabled: false

keyCloak:
  enabled: false

graderSetupService:
  enabled: false
  graderSetupImage: illumidesk/grader-setup-app:latest
  graderImage: illumidesk/grader-notebook:latest
