{{ if .Values.keyCloak.enabled }}
apiVersion:  v1
kind:  ConfigMap
type:  Opaque
metadata: 
  namespace:  {{ .Release.Namespace }}
  name:  keycloak-postgres-secrets-{{ .Release.Namespace }}
data: 
  KEYCLOAK_PASSWORD: {{ .Values.keyCloak.keycloak_password | b64enc }}
  DB_PASSWORD: {{ .Values.keyCloak.db_password | b64enc }}

{{ end }}